### ISSUE TITLE
mljar model class

### ISSUE THREAD

**Issue by maksymiuks** [mljar/mljar-api-R#21]
First of all, very nice api, I love to use it.

But I have one small problem. Can You please change class of object returned by mljar_fit to something that will stright away indicate on mljar? Right now it is simple list and it is hard for me to check if given model is indeed mljar model.

**Comment by pplonski** [comment]
Thanks! Can you suggest the solution?

**Comment by maksymiuks** [comment]
PR ready

**Comment by maksymiuks** [comment]
Also. Is it possbile for that list to contain not only field with experiment title but with project title aswell?
